name: Deploy Backend to cPanel

on:
  push:
    branches:
      - dev  # ✅ Trigger only on dev branch

jobs:
  deploy:
    name: Upload Backend Files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via FTP (only contents of finflow-backend)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /api/
          exclude: |
            .git*
            **/.git/**
            **/.git*/**
            **/.github/**
            **/.gitignore
            **/.gitattributes
            **/*.zip
            README.md
